version: 2

force_token: github

before:
  hooks:
    - cargo fetch --locked

builds:
  - builder: rust
    single_build: false
    binary: grove
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
    env:
      - CGO_ENABLED=0

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

nfpms:
  - id: grove
    package_name: grove
    vendor: ziim
    homepage: https://github.com/ziim/grove
    maintainer: ziim <[email protected]>
    description: A TUI for managing multiple Claude Code agents with git worktree isolation
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
