version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    binary: grove
    flags:
      - --release
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    env:
      - CGO_ENABLED=0

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  split: true

brews:
  - name: grove
    homepage: https://github.com/ziim/grove
    description: A TUI for managing multiple Claude Code agents with git worktree isolation
    license: MIT
    repository:
      owner: ziim
      name: homebrew-grove
      branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "grove"
